#pragma once
#ifndef FLAGS_H
#define FLAGS_H
#include <SDL2/SDL.h>
#define HARDWARE 1
#define SOFTWARE !HARDWARE

#define SDL_WINDOW_POS (SDL_WINDOWPOS_CENTERED)
#define SDL_WINDOW_FLAGS (SDL_WINDOW_HIDDEN | SDL_WINDOW_ALWAYS_ON_TOP)
#define SDL_INIT_FLAGS (SDL_INIT_EVENTS | SDL_INIT_VIDEO | SDL_INIT_TIMER)

#define GENERIC_RENDERER_FLAGS SDL_RENDERER_TARGETTEXTURE

#if SOFTWARE == 1
#define RENDERER_FLAGS (SDL_RENDERER_SOFTWARE | GENERIC_RENDERER_FLAGS)
#else // SOFTWARE == 1
#define RENDERER_FLAGS (SDL_RENDERER_ACCELERATED | GENERIC_RENDERER_FLAGS)
#endif // SOFTWARE == 1
#endif // FLAGS_H
